# Generated by Django 4.2.6 on 2023-11-30 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=500)),
                ('Text', models.TextField()),
                ('DateTime', models.DateTimeField(auto_now=True)),
                ('Closed', models.BooleanField(default=False)),
                ('Deleted', models.BooleanField(default=False)),
                ('Subject_Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.category')),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.TextField()),
                ('DateTime', models.DateTimeField(auto_now=True)),
                ('Verified_Answer', models.BooleanField(default=False)),
                ('Deleted', models.BooleanField(default=False)),
                ('Replied_To', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.answer')),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.subject')),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
